---
title: "Home"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---

This repository contains simulation results related to mvSuSiE-RSS.

* [20200229 First simple simulation](mmbr_rss_simulation_1.html)

    [Residual variance problem](mmbr_rss_simulation_1_problem.html)
    
* [20200527 First Simulation with Missing](mmbr_missing_1.html)

    [RSS from missing data](mmbr_rss_missing_1.html)

* [20200616 Second simulation with Missing](mmbr_missing_0616.html)

    Results for Missing data with individual level data seems ok. The results from RSS need further investigation, the FDR is very high.
    
    RSS problem example: [Eg1](mmbr_missing_rss_problem1.html), [Eg2](mmbr_missing_rss_problem2.html)

* [20200721 Second simulation for RSS using GTEx](mmbr_rss_simulation_3.html)


mvSuSiE full data application on GTEx

* [New Profile using GTEx](GTExprofile2.html), [Profile using GTEx](GTExprofile.html)

    [Problem](GTExprofileProblem.html); [Problem continue](GTExprofileProblem2.html); 
    
* [mvSuSiE missing data imputation](mmbr_missing_imputation.html)


UKB simulations:

* [Create simulation priors](create_simulation_priors.html)

* [Simulation Data Driven Prior](priors_ed_20220619.html)

* [Result20220619](mvsusie_rss_ukb_simulation_20220619.html)

    [UKB cannonical vs random](ukb_bloodcells_20220619_ukb_canonicalvsrandom.html)
    
    [Artificial conditional lfsr](ukb_bloodcells_20220619_lfsr.html)

UKB analysis:
  
* [Result20220619](ukb_bloodcells_20220619.html)

Previous results

* [Simulation Data Driven Prior](priors_ed.html)

* [Result20210107](mmbr_rss_ukb_simulation_20210107.html)

    [lfsr using cannonical priors](mmbr_rss_ukb_simulation_20210107_naiveprior_lfsr_problem.html)

* [Result20210313](mmbr_rss_ukb_simulation_20210313.html)

    [Random vs Default](mmbr_rss_ukb_simulation_20210313_RandomvsDefault.html)

* [Compare with PAINTOR](mmbr_rss_ukb_simulation_paintor.html)

