---
title: "Data driven prior from ED"
author: "Yuxin Zou"
date: "12/21/2020"
output: 
  workflowr::wflow_html:
    code_folding: hide
---

The result is from [this notebook](https://github.com/gaow/mvarbvs/blob/master/analysis/20201221_ukb_Prepare_ED_prior.ipynb).

## Artificial mixture

```{r}
dat_a = readRDS('data/mmbr_ukb_simulation/artificial_mixture_ukb.FL_PC3.EDmash.rds')
names(dat_a)
```
```{r}
names(dat_a$w) = names(dat_a$U)
barplot(dat_a$w, las=2, cex.names = 0.7)
```

```{r}
tol = 1E-15
names(dat_a$U)[which(dat_a$w>tol)]
```

The component with strongest weight is tXX.

```{r}
plot_sharing = function(X) {
clrs <- colorRampPalette(rev(c("#D73027","#FC8D59","#FEE090","#FFFFBF",
                               "#E0F3F8","#91BFDB","#4575B4")))(128)
lat <- cov2cor(X)
lat[lower.tri(lat)] <- NA
n <- nrow(lat)
print(lattice::levelplot(lat[n:1,],col.regions = clrs,xlab = "",ylab = "",
                colorkey = TRUE,at = seq(-1,1,length.out = 128),
                scales = list(cex = 0.6,x = list(rot = 45))))
}
```

```{r}
plot_sharing(dat_a$U$XX)
```
```{r}
plot_sharing(dat_a$U$tFLASH)
```

```{r}
plot_sharing(dat_a$U$FLASH_3)
```
```{r}
plot_sharing(dat_a$U$FLASH_4)
```

## UKB bloodcells mixture

```{r}
dat_ukb = readRDS('data/mmbr_ukb_simulation/ukb_bloodcells_mixture.FL_PC3.EDmash.rds')
```

```{r}
names(dat_ukb$w) = names(dat_ukb$U)
barplot(dat_ukb$w, las=2, cex.names = 0.7)
```
```{r}
names(dat_ukb$U)[which(dat_ukb$w>tol)]
```

```{r}
plot_sharing(dat_ukb$U$XX)
```
```{r}
plot_sharing(dat_ukb$U$FLASH_8)
```

```{r}
plot_sharing(dat_ukb$U$tFLASH)
```
