---
title: "mvSuSiE RSS application on UKB blood cell traits"
author: "Yuxin Zou"
date: "06/19/2022"
output:
  workflowr::wflow_html:
    code_folding: hide
---

```{r}
library(data.table)
library(dplyr)
library(ggplot2)
regions = fread('data/analysis_20220619/region_units.txt', header = FALSE)$V1
regions_info = fread('data/analysis_20220619/regions.csv')
colnames(regions_info) = c('chr', 'start', 'end', 'length', '-log10p', 'numsnps')
regions_info$Region = paste0('bloodcells_chr', regions_info$chr, '.',
                             regions_info$start, '.', regions_info$end)

LD_cov = 'original'
resid_cor = 'Ycor'
```

```{r}
# mvsusie_rss
res_mvrss = fread(paste0('data/analysis_20220619/LD', LD_cov, '.', resid_cor, '.mvsusierss.CS_purity0.5.CS_lfsr0.01.summary.csv'))
res_mvrss = res_mvrss %>% arrange(CHR, POS)
## make sure the purity > 0.5 (this should not filter out any CSs, but it filters out variants with pip > 0.05, but not in any CSs)
res_mvrss = res_mvrss %>% filter(purity > 0.5)

# summary region level
res_mvrss_region = res_mvrss %>% group_by(Region) %>% summarize(CS_num = n_distinct(CS, na.rm=TRUE))
cat('number of regions with CSs \n')
sum(res_mvrss_region$CS_num > 0) # 921
cat('number of CSs \n')
sum(res_mvrss_region$CS_num) # 3396
```

```{r}
# summary CS level
res_mvrss_CS = res_mvrss %>% select(Region, CS, purity, CS_trait) %>%
  group_by(Region, CS) %>% mutate(CS_size = n()) %>% ungroup() %>% distinct()

trait = c("WBC_count", "RBC_count", "Haemoglobin", "MCV", "RDW", "Platelet_count",
          "Plateletcrit", "PDW", "Lymphocyte_perc", "Monocyte_perc", "Neutrophill_perc",
          "Eosinophill_perc", "Basophill_perc", "Reticulocyte_perc", "MSCV", "HLR_perc")

rename = list('WBC_count' = 'WBC#',
              'RBC_count' = 'RBC#',
              'Haemoglobin' = 'HGB',
              'MCV' = 'MCV',
              'RDW' = 'RDW',
              "Platelet_count" = 'PLT#',
              "Plateletcrit" = 'PCT',
              "PDW" = 'PDW',
              "Lymphocyte_perc" = 'LYMPH%',
              "Monocyte_perc" = 'MONO%',
              "Neutrophill_perc" = 'NEUT%',
              "Eosinophill_perc" = 'EO%',
              "Basophill_perc" = 'BASO%',
              "Reticulocyte_perc" = 'RET%',
              "MSCV" = 'MSCV',
              "HLR_perc" = 'HLR%')
for(name in trait){
  tmp = sapply(res_mvrss_CS$CS_trait, function(x){
    cstrait = grep(name, x)
    ifelse(length(cstrait) > 0, cstrait, 0)
  })
  res_mvrss_CS[ , ncol(res_mvrss_CS) + 1] <- unname(tmp)
  colnames(res_mvrss_CS)[ncol(res_mvrss_CS)] <- name
}

res_mvrss_CS$CS_trait_num = rowSums(res_mvrss_CS[,6:21])

bloodcells_col = cbind(trait,
                       c('Compound white cell', 'Mature red cell', 'Mature red cell',
                         'Mature red cell', 'Mature red cell', 'Platelet', 'Platelet',
                         'Platelet', 'Compound white cell', 'Compound white cell',
                         'Compound white cell', 'Compound white cell', 'Compound white cell',
                         'Immature red cell', 'Mature red cell','Immature red cell'),
                       c('#33cccc', 'red', 'red', 'red', 'red',
                         '#cc66ff', '#cc66ff', '#cc66ff',
                         '#33cccc', '#33cccc', '#33cccc', '#33cccc', '#33cccc',
                         'pink', 'red', 'pink'))
res_mvrss_CS = res_mvrss_CS %>% mutate(CS_WB = WBC_count + Lymphocyte_perc + Monocyte_perc +
                                         Neutrophill_perc + Eosinophill_perc + Basophill_perc,
                                       CS_RB = RBC_count + Haemoglobin + MCV + RDW +
                                         Reticulocyte_perc + MSCV + HLR_perc,
                                       CS_RB2 = RBC_count + Haemoglobin,
                                       CS_PL = Platelet_count + Plateletcrit + PDW)

## summary of CS size
# ggplot(res_mvrss_CS, aes(CS_size)) + geom_histogram(aes(y = ..density..), binwidth = 1) +
#   labs(x = 'CS size', y = 'Proportion of CSs') + lims(x = c(1,50))
cat('median CS size \n')
median(res_mvrss_CS$CS_size)
cat('number of CS size == 1 \n')
sum(res_mvrss_CS$CS_size == 1)
cat('median CS purity \n')
median(res_mvrss_CS$purity)
```

```{r CS_shares, fig.width=8, fig.height=7}
## CS sharing
# pdf('~/Documents/GitHub/Yuxin_Thesis/mvsusie_rss/figures/ukbbloodcells_CS_traits.pdf', height = 7, width = 8)
p = ggplot(res_mvrss_CS %>% filter(CS_trait_num > 0), aes(CS_trait_num)) +
  geom_bar(aes(y = ..prop.., group = 1)) +
  labs(x = 'Number of traits', y = 'Proportion of CSs') + theme_bw() +
  theme(axis.title = element_text(size = 15), axis.text = element_text(size = 12),
        title = element_text(size=15)) +
  ggtitle('A. Shared CSs across traits')
p
pdf(paste0('output/analysis_20220619/ukbbloodcells_CS_traits_LD', LD_cov, '.', resid_cor, '.pdf'), height = 7, width = 8)
p
dev.off()
```

```{r pairwise_share, fig.height=8, fig.width=8}
## pairwise sharing
get_pairwise_sharing = function(dat){
  R = ncol(dat)
  S = diag(R)
  for(i in 1:(R-1)){
    for(j in (i+1):R){
      sig_i=which(dat[,i] == 1)
      sig_j=which(dat[,j] == 1)
      S[i,j] = length(intersect(sig_i, sig_j))/length(union(sig_i,sig_j))
    }
  }
  S[lower.tri(S, diag = FALSE)] = t(S)[lower.tri(S, diag = FALSE)]
  colnames(S) = row.names(S) = colnames(dat)
  return(S)
}
dat = res_mvrss_CS[,6:21]
CS_trait_sharing = get_pairwise_sharing(dat)
colnames(CS_trait_sharing) = rownames(CS_trait_sharing) = sapply(colnames(CS_trait_sharing), function(x) rename[[x]])
trait_new_order = c("RBC#", "HGB", "MCV", "RDW", "MSCV", "RET%", "HLR%", "PLT#", "PCT", "PDW",
                    "WBC#", "LYMPH%", "MONO%", "NEUT%", "EO%", "BASO%")
traits_index = match(trait_new_order, colnames(CS_trait_sharing))
CS_trait_sharing = CS_trait_sharing[traits_index, traits_index]
CS_trait_sharing[lower.tri(CS_trait_sharing)] <- NA
n <- nrow(CS_trait_sharing)
melted_cormat <- reshape2::melt(CS_trait_sharing[n:1,], na.rm = TRUE)
clrs <- colorRampPalette(rev(c("#D73027","#FC8D59","#FFFFBF","#FFFFFF"
                               # "#FEE090", "#E0F3F8","#91BFDB","#4575B4"
)))(64)
p = ggplot(data = melted_cormat, aes(Var2, Var1, fill = value))+
  geom_tile(color = "white")+ggtitle('B. Pairwise sharing of CSs') +
  # scale_fill_gradient(low="white", high="red2") +
  scale_fill_gradientn(colors = clrs, limit = c(0,1)) +
  theme_minimal()+
  coord_fixed() +
  theme(
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
    axis.text.x = element_text(color=bloodcells_col[,3][traits_index], size=12,angle=45,hjust=1),
    axis.text.y = element_text(color=rev(bloodcells_col[,3][traits_index]), size=12),
    title =element_text(size=15),
    # panel.grid.major = element_blank(),
    panel.border = element_blank(),
    panel.background = element_blank(),
    axis.ticks = element_blank(),
    legend.justification = c(1, 0),
    legend.position = c(0.6, 0),
    legend.direction = "horizontal")+
  guides(fill = guide_colorbar(title="proportion of CSs \nthat are shared", barwidth = 7, barheight = 1,
                               title.position = "top", title.hjust = 0.5))
p
pdf(paste0('output/analysis_20220619/ukbbloodcells_CS_sharing_LD', LD_cov, '.', resid_cor, '.pdf'), height=8, width = 8)
p
dev.off()
```

```{r}
# susierss
if(LD_cov == 'original'){
  res_rss = fread('data/analysis_20220619/susierss.notrem.CS_purity0.5.summary.csv')
}else{
  res_rss = fread('data/analysis_20220619/susierss.rem.CS_purity0.5.summary.csv')
}

trait = c("WBC_count", "RBC_count", "Haemoglobin", "MCV", "RDW", "Platelet_count",
          "Plateletcrit", "PDW", "Lymphocyte_perc", "Monocyte_perc", "Neutrophill_perc",
          "Eosinophill_perc", "Basophill_perc", "Reticulocyte_perc", "MSCV", "HLR_perc")

res_rss_CS = c()
res_rss_region = c()
for(name in trait){
  cat(paste0(name, '\n'))
  tmp = res_rss %>% filter(trait == name)
  ## summary region level
  tmp_region = tmp %>% group_by(trait, Region) %>% summarize(CS_num = n_distinct(CS, na.rm=TRUE))
  
  res_rss_region = rbind(res_rss_region, tmp_region)
  cat(paste0('total regions with CS: ', sum(tmp_region$CS_num > 0), '\n'))
  cat(paste0('total CSs: ', sum(tmp_region$CS_num), '\n'))
  
  ## summary CS level
  tmp_CS = tmp %>% filter(!is.na(CS)) %>% select(Region, trait, CS, purity) %>%
    group_by(trait, Region, CS) %>% mutate(CS_size = n()) %>% ungroup() %>% distinct()
  res_rss_CS = rbind(res_rss_CS, tmp_CS)
  # ggplot(res_suff_wbc_CS %>% filter(CS_size < 50), aes(CS_size)) + geom_bar(aes(y = stat(count) / sum(count))) +
  #   labs(x = 'CS size', y = 'Proportion of CSs')
  cat('summary of CS sizes \n')
  print(summary(tmp_CS$CS_size))
}
```

```{r cs_num_compare, fig.height=10, fig.width=6}
## CS summary
bloodcells_col = cbind(trait,
                       c('Compound white cell', 'Mature red cell', 'Mature red cell',
                         'Mature red cell', 'Mature red cell', 'Platelet', 'Platelet',
                         'Platelet', 'Compound white cell', 'Compound white cell',
                         'Compound white cell', 'Compound white cell', 'Compound white cell',
                         'Immature red cell', 'Mature red cell','Immature red cell'),
                       c('#33cccc', 'red', 'red', 'red', 'red',
                         '#cc66ff', '#cc66ff', '#cc66ff',
                         '#33cccc', '#33cccc', '#33cccc', '#33cccc', '#33cccc',
                         'pink', 'red', 'pink'))
res_rss_CS_size = res_rss_CS %>% group_by(trait) %>% summarise(grp.mean=mean(CS_size), grp.median = median(CS_size))

CS_compare = res_rss_region %>% group_by(trait) %>% summarize(CSnumber = sum(CS_num))
tmp = colSums(res_mvrss_CS[,6:21])
CS_compare$mvCSnumber = tmp[match(CS_compare$trait, names(tmp))]
CS_compare$type = bloodcells_col[match(CS_compare$trait, bloodcells_col[,1]),2]
CS_compare$trait = sapply(CS_compare$trait, function(x) rename[[x]])
p = ggplot(CS_compare, aes(x = CSnumber, y = mvCSnumber, color = type)) + geom_point() +
  scale_color_manual(values = c('#33cccc', 'pink', 'red', '#cc66ff')) +
  geom_abline(slope=1,intercept = 0, linetype=2) +
  geom_text(aes(label=trait),vjust = "inward", hjust = "inward", size=3.5) +
  labs(x = 'SuSiE',
       y = 'mvSuSiE') + theme_bw() +
  theme(legend.position = "none",
        title = element_text(size=15)) +
  ggtitle('C. Number of significant CSs')
p
pdf(paste0('output/analysis_20220619/ukbbloodcells_CS_num_LD', LD_cov, '.', resid_cor,'.pdf'), height=10, width = 6)
p
dev.off()
```

```{r cs_size_compare, fig.height=5.5, fig.width=4}
CS_size_compare = res_rss_CS %>% group_by(trait) %>% summarize(CSsize = median(CS_size))
tmp = apply(res_mvrss_CS[, 6:21], 2, function(x) median(res_mvrss_CS$CS_size[x==1]))
CS_size_compare$mvCSsize = tmp[match(CS_size_compare$trait, names(tmp))]
CS_size_compare$type = bloodcells_col[match(CS_size_compare$trait, bloodcells_col[,1]),2]
CS_size_compare$trait = sapply(CS_size_compare$trait, function(x) rename[[x]])
CS_size_compare = reshape2::melt(CS_size_compare)
CS_size_compare$variable = as.character(CS_size_compare$variable)
CS_size_compare$variable[CS_size_compare$variable == 'CSsize'] = 'SuSiE'
CS_size_compare$variable[CS_size_compare$variable == 'mvCSsize'] = 'mvSuSiE'
CS_size_compare$trait = factor(CS_size_compare$trait, levels = trait_new_order)
p = ggplot(CS_size_compare, aes(x = trait, y=value, color=variable)) + geom_point() +
  ylab('median size of CSs') + theme_bw() +
  ggtitle('D. CS size') +
  labs(color='method') +
  scale_color_manual(values = c("SuSiE" = "grey", "mvSuSiE" = "black")) +
  scale_x_discrete(limits = rev(levels(CS_size_compare$trait))) +
  coord_flip() +
  theme(title = element_text(size=13),
        axis.text.y = element_text(color = bloodcells_col[,3][rev(traits_index)]), 
        axis.title.y = element_blank(),
        legend.position=c(1, 1.08),
        legend.direction="horizontal",
        legend.justification = c("right","top"),
        legend.title=element_blank(),
        legend.background = element_rect(fill='transparent'))
p
pdf(paste0('output/analysis_20220619/ukbbloodcells_CS_size_LD', LD_cov, '.', resid_cor,'.pdf'), height=5.5, width = 4)
p
dev.off()
```
